apiVersion: batch/v1
kind: Job
metadata:
  name: bakta-job
  namespace: bakta-test  
spec:
  template:
    spec:
      containers:
      - name: bakta-job
        image: quay.io/mariusdieckmann/bakta-web-job
        volumeMounts:
          - mountPath: /db
            name: database-pb
          - mountPath: /cache
            name: cache-volume
        env:
          - name: DownloaderEnvConfig
            #value: "download -b baktatest -k data/demo-fasta.fasta -d /data -e s3.computational.bio.uni-giessen.de"
            value: "download --buckets baktatest,"
          - name: BaktaEnvConfig
            value: "--db /db /demo-fasta.fasta"
          - name: UploaderEnvConfig
            value: "upload -e s3.computational.bio.uni-giessen.de -k data/result/1 -b baktatest -f /results.tar.gz"
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: database-pb
          persistentVolumeClaim:
            claimName: bakta-test
      restartPolicy: Never
  backoffLimit: 4